[project]
name = "tna-utilities"
version = "1.2.0"
requires-python = ">=3.10"
authors = [
  {name = "Andrew Hosgood", email = "andrew.hosgood@nationalarchives.gov.uk"},
]
description = "A library of common National Archives Python functions"
readme = "README.md"
license = "MIT"
license-files = ["LICENCE"]
keywords = ["utilities", "library", "python", "the national archives", "tna"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://pypi.org/project/tna-utilities/"
Documentation = "https://nationalarchives.github.io/python-utilities/"
Repository = "https://github.com/nationalarchives/python-utilities"
"Bug Tracker" = "https://github.com/nationalarchives/python-utilities/issues"
Changelog = "https://github.com/nationalarchives/python-utilities/blob/main/CHANGELOG.md"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
exclude = ["docs*", "tasks*", "tests*"]
