name: CI

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  check_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check formatting
        run: ./tasks/checkformat.sh

  test:
    strategy:
      matrix:
        python-version: ["3.14", "3.13", "3.12", "3.11", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies and run tests
        run: ./tasks/test.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
      - name: Install Poetry
        run: pipx install poetry
      - name: Install dependencies and build package
        run: ./tasks/build.sh
