name: CI

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.14", "3.13", "3.12", "3.11", "3.10"]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check formatting
        # TODO: Change from preview to latest image when available
        run: docker run --rm -v "$(pwd)":/app/ ghcr.io/nationalarchives/tna-python-dev:preview checkformat
      - name: Run tests
        run: python -m unittest discover test
