name: CI

on:
  workflow_dispatch:
  push:
    # branches:
    #   - main
    #   - feature/*

jobs:
  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-verion: [3.13, 3.12, 3.11, 3.10, 3.9]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Python tests
        run: python -m unittest discover test
